[project]
name = "payipa-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.12.1",
    "docker>=7.1.0",
    "trio>=0.32.0",
]
